import Head from "next/head";
import Image from "next/image";
import { css } from "@emotion/react";
import NavBar from "../components/NavBar";
import FileInput from "../components/FileInput";
import FileConvertor from "../components/FileConvertor";

export default function Home() {
  return (
    <div
      css={css`
        height: 100vh;
        width: 100wv;
      `}
    >
      <Head>
        <title>base 64 encoder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <NavBar items={[{ title: "base 64 encoder", href: "/" }]}></NavBar>
      </header>
      <main
        css={css`
          height: 90%;
          display: flex;
          flex-direction: column;
          align-items: center;
        `}
      >
        <FileInput expended={false}></FileInput>
        <FileConvertor></FileConvertor>
      </main>
    </div>
  );
}
